trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '3edf302c-c1a5-441c-adfb-1627a900394b'
  webAppName: 'YOUR-APP-NAME'

stages:

# ================= BUILD =================
- stage: Build
  jobs:
  - job: Build
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Build React App'

    # Copy build files
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    # Archive build
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)/app.zip'
      artifact: drop


# ================= DEPLOY =================
- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: drop

          - task: AzureRmWebAppDeployment@4
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              WebAppName: $(webAppName)
              packageForLinux: '$(Pipeline.Workspace)/drop/app.zip'